version: '2' 
services:
  #web:
  #  build: flask-app
  #  ports:
  #   - "5000:5000"
  #  volumes:
  #  # - .:/code
  #    - ./flask-app:/usr/src/app
  website:
#    image: php:apache
    build: website
    volumes:
      - ./website:/var/www/html
    ports:
      - 5000:80

  mysql:
    build: mysql-server
    environment:
      #MYSQL_DATABASE: docker_test1
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: 0.0.0.0
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
